[package]
name = "nvi"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
reqwest = { version = "0.12.5", features = ["blocking"] }
rpassword = "7.3.1"
toml = "0.8.19"
