[standard]
api = true
debug = true
# valid comment
directory = "envs"
environment = "debug"
execute = ["echo", "Hello World!"]
files = [ "test1.env", "test2.env", "test3.env" ]
print = true
project = "rust"
# valid comment
required = [ "TEST1", "TEST2", "TEST3" ]
save = true

[partial]
debug = true
environment = "debug"
execute = ["echo", "Hello World!"]
files = [ "test1.env", "test2.env", "test3.env" ]
