pub const A: u8 = 'A';
pub const Z: u8 = 'Z';
pub const ZERO: u8 = '0';
pub const NINE: u8 = '9';
pub const NULL_CHAR: u8 = 0;
pub const LINE_DELIMITER: u8 = '\n';
pub const ASSIGN_OP: u8 = '=';
pub const HASH: u8 = '#';
pub const UNDERLINE: u8 = '_';
pub const DOLLAR_SIGN: u8 = '$';
pub const OPEN_BRACE: u8 = '{';
pub const CLOSE_BRACE: u8 = '}';
pub const CLOSE_PAREN: u8 = ')';
pub const BACK_SLASH: u8 = '\\';
pub const DOUBLE_QOUTE: u8 = '"';
pub const SINGLE_QOUTE: u8 = '\'';
pub const CARRIAGE_RETURN: u8 = '\t';
pub const SPACE: u8 = ' ';
pub const DOT: u8 = '.';

pub const SPECIAL_CHARS = [_]u8{ NULL_CHAR, LINE_DELIMITER, ASSIGN_OP, HASH, DOLLAR_SIGN, BACK_SLASH };
